#!/usr/bin/env perl

use strict;
use warnings;
use lib $ENV{C_TAP_SOURCE} . "/tests-lib/perl5";

use afstest qw(obj_path);
use Test::More tests=>4;
use POSIX qw(:sys_wait_h :signal_h);

my $port = 4000;
my $service = 1234;
my $server = obj_path("tests/rx/simple-server");
my $client = obj_path("tests/rx/simple-client");
my $server_pid;

# Start up the server
$server_pid = open(my $server_fh, '-|', $server, $port, $service);
if (!defined($server_pid)) {
    die("Failed to run $server: $!");
}

# Wait for the server to finish starting
while (my $line = <$server_fh>) {
    chomp($line);
    diag($line);
}

# Server is now ready to receive calls

pass("Started server");

# Start up a client, and run a test
my $message = 'Hello OpenAFS';
my $expected = 'Uryyb BcraNSF';
my $got = qx($client localhost $port $service "$message");
chomp($got);

is(0, $?, "client ran successfully");
is($expected, $got, "rot13 performed successfully");

# Kill the server process
kill("TERM", $server_pid);

close($server_fh);
my $ecode = ${^CHILD_ERROR_NATIVE};
if (WIFSIGNALED($ecode) && WTERMSIG($ecode) == SIGTERM) {
    pass("Server died with SIGTERM");
} elsif (WIFSIGNALED($ecode)) {
    fail("Server died with signal ".WTERMSIG($ecode));
} else {
    fail("Server exited with code". WEXITSTATUS($ecode));
}
